version: "1"

services:
  postgres:
    image: bitnami/postgresql:15.3.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=q
      - POSTGRESQL_TIMEZONE=Europe/Istanbul
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=tr-TR
#    volumes:
#      - C:\Users\Bilge\DockerPersistence\postgre\data:/bitnami/postgresql
    restart: always